import 'package:chili_pepper_test/insert.dart';
import 'package:chili_pepper_test/accurate_result.dart';
import 'package:chili_pepper_test/graph_page.dart';
import 'package:chili_pepper_test/chili_pepper_classes.dart';
import 'package:chili_pepper_test/landing_page.dart'; // Import LandingPage
import 'package:chili_pepper_test/profile_page.dart'; // Import ProfilePage
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // <- generated by FlutterFire CLI

import 'package:chili_pepper_test/custom_page_transition.dart'; // Import CustomPageTransitionsBuilder

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Firebase Realtime DB Demo',
      theme: ThemeData(
        primarySwatch: Colors.red,
        pageTransitionsTheme: PageTransitionsTheme(
          builders: {
            TargetPlatform.android: CustomPageTransitionsBuilder(),
            TargetPlatform.iOS: CustomPageTransitionsBuilder(),
          },
        ),
      ),
      home: LandingPage(), // Changed from HomePage() to LandingPage()
      routes: {
        '/accurate-result': (context) => AccurateResultPage(),
        '/graph': (context) => GraphPage(),
        '/chili-pepper-classes': (context) => ChiliPepperClassesPage(),
        '/profile': (context) => ProfilePage(), // Add ProfilePage route
      },
    );
  }
}
